# Generated by Django 4.0.5 on 2022-06-22 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bathroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_bathroom', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bedroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_bedroom', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_image', models.ImageField(upload_to='uploads/pics/furnitures')),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_garage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Flat', 'Flat'), ('Estate', 'Estate'), ('Duplex', 'Duplex')], default='Flat', max_length=20)),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('display_image', models.ImageField(upload_to='uploads/pics/sale')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='uploads/pics/rent')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='uploads/pics/rent')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='uploads/pics/rent')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='uploads/pics/rent')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='uploads/pics/rent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bathroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.bathroom')),
                ('bedroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.bedroom')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.garage')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.location')),
                ('state', models.ForeignKey(default='All', on_delete=django.db.models.deletion.CASCADE, to='pages.state')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Flat', 'Flat'), ('Hostel', 'Hostel')], default='Flat', max_length=20)),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('display_image', models.ImageField(upload_to='uploads/pics/rent')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='uploads/pics/rent')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='uploads/pics/rent')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='uploads/pics/rent')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='uploads/pics/rent')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='uploads/pics/rent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bathroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.bathroom')),
                ('bedroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.bedroom')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.garage')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.location')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.state')),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Any Land', 'Any Land'), ('50 x 100', '50 x 100'), ('100 x 100', '100 x 100'), ('100 x 200', '100 x 200'), ('200 x 200', '200 x 200'), ('1 acre', '1 acre')], default='Any Land', max_length=20)),
                ('price', models.FloatField()),
                ('display_image', models.ImageField(upload_to='uploads/pics/land')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.location')),
                ('state', models.ForeignKey(default='All', on_delete=django.db.models.deletion.CASCADE, to='pages.state')),
            ],
        ),
    ]
