# Generated by Django 4.0.5 on 2022-06-23 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_land_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.state'),
        ),
    ]
