# Generated by Django 4.0.5 on 2022-06-25 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_land_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='bathroom',
            new_name='toilet_and_bathroom',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='bathroom',
            new_name='toilet_and_bathroom',
        ),
    ]
